
- name: Create directories to attach docker volumes
  file: path=/var/lib/nexus/sonatype-work state=directory mode=0777 owner=root group=root

- name: Start dockerized nexus
  docker: name=nexus image=sonatype/nexus state=started ports="127.0.0.1:8081:8081" expose=8081 volumes=/var/lib/nexus/sonatype-work:/sonatype-work restart_policy=always


- name: Install httpd
  yum: name=httpd state=present

- name: Configure httpd as proxy to nexus
  copy: src=nexus.conf dest=/etc/httpd/conf.d/nexus.conf mode=0644 owner=root group=root
  notify:
  - restart httpd

- name: Enable and start httpd
  service: name=httpd enabled=true state=started


- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable selinux
  selinux: policy=targeted state=permissive
