- name: Create directories to attach docker volumes
  file: path=/var/lib/sonarqube/{{ item }} state=directory mode=0777 owner=root group=root
  with_items:
  - postgresql
  - conf
  - plugins
  - extensions

- name: Start postgresql
  docker:
    name: postgresql
    image: postgres
    state: started
    restart_policy: always
    expose: 5432
    volumes:
    - /var/lib/sonarqube/postgresql:/var/lib/postgresql/data
    env:
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_USER: sonarqube


- name: Start dockerized sonarqube
  docker:
    name: sonarqube
    image: sonarqube:6.6
    state: started
    restart_policy: always
    ports: "127.0.0.1:9000:9000"
    expose: 9000
    volumes:
    - /var/lib/sonarqube/conf:/opt/sonarqube/conf
    - /var/lib/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    - /var/lib/sonarqube/extensions:/opt/sonarqube/extensions
    links:
    - postgresql:postgresql
    env:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql/sonarqube



- name: Install httpd
  yum: name=httpd state=present

- name: Configure httpd as proxy to nexus
  copy: src=sonarqube.conf dest=/etc/httpd/conf.d/sonarqube.conf mode=0644 owner=root group=root
  notify:
  - restart httpd

- name: Enable and start httpd
  service: name=httpd enabled=true state=started

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable selinux
  selinux: policy=targeted state=permissive
