---
- name: Create directories to attach docker volumes
  file: path=/var/lib/nginx/{{ item }} state=directory mode=0777 owner=root group=root
  with_items:
    - conf.d
    - html

- name: Start nginx
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/nginx/conf.d:/etc/nginx/conf.d
      - /var/lib/nginx/html:/usr/share/nginx/html

- name: Configure nginx
  template:
    src: atsc.conf.j2
    dest: /var/lib/nginx/conf.d/atsc.conf.j2
    mode: 0644
    owner: root
    group: root
    backup: yes
  notify:
    - restart nginx

- name: Configure homepage
  copy:
    src: index.html
    dest: /var/lib/nginx/html/index.html
    mode: 0644
    owner: root
    group: root
    backup: yes
  notify:
    - restart nginx
