---
- name: Create directories to attach docker volumes
  file: path=/var/lib/nginx/{{ item }} state=directory mode=0777 owner=root group=root
  with_items:
    - conf.d
    - html

- name: Start nginx
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/nginx/conf.d:/etc/nginx/conf.d
      - /var/lib/nginx/html:/usr/share/nginx/html
