- hosts: all
  gather_facts: True

- hosts: sonarqube
  roles:
  - docker-app-server
  - sonarqube
  tags:
  - sonarqube

- hosts: nexus
  roles:
  - docker-app-server
  - nexus
  tags:
  - nexus

- hosts: jenkins
  roles:
  - docker-app-server
  - jenkins
  tags:
  - jenkins

- hosts: gitea
  roles:
  - docker-app-server
  - gitea
  tags:
  - gitea

- hosts: gitlab
  roles:
  - gitlab
  tags:
  - gitlab

#- hosts: taiga
#  - docker-app-server
#  roles:
#  - taiga
#  tags:
#  - taiga

- hosts: nginx
  roles:
  - nginx
  tags:
  - nginx
