- name: Install docker
  yum: name={{ item }} state=present
  with_items:
  - docker
  - docker-python

- name: Enable and start docker
  service: name=docker enabled=true state=started

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable selinux
  selinux: policy=targeted state=permissive
