- name: Create directories to attach docker volumes
  file: path=/var/lib/gitlab/{{ item }} state=directory mode=0777 owner=root group=root
  with_items:
    - config
    - logs
    - data

- name: Start gitlab
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    state: started
    restart_policy: always
#    published_ports:
#      - 127.0.0.1:9080:80
#      - 127.0.0.1:9443:443
#    expose:
#      - 80
#      - 443
    volumes:
      - /var/lib/gitlab/config:/etc/gitlab
      - /var/lib/gitlab/logs:/var/log/gitlab
      - /var/lib/gitlab/data:/var/opt/gitlab

- name: Wait until the gitlab config is present before continuing
  wait_for:
    path: /var/lib/gitlab/config/gitlab.rb

- name: Set external_url
  lineinfile:
    dest: "/var/lib/gitlab/config/gitlab.rb"
    regexp: '^external_url'
    insertafter: '# external_url'
    line: "external_url 'http://{{ public_hostname }}/gitlab/'"
  notify:
    - restart gitlab

- name: Set external_url
  lineinfile:
    dest: "/var/lib/gitlab/config/gitlab.rb"
    regexp: '^external_url'
    insertafter: '# external_url'
    line: "external_url 'http://{{ ansible_default_ipv4.address }}/gitlab/'"
  notify:
    - restart gitlab
  when: public_hostname == "none"

#- name: Install httpd
#  yum: name=httpd state=present

#- name: Configure httpd as proxy to gitlab
#  copy: src=gitlab.conf dest=/etc/httpd/conf.d/gitlab.conf mode=0644 owner=root group=root
#  notify:
#    - restart httpd

#- name: Enable and start httpd
#  service: name=httpd enabled=true state=started
